#ifndef TMCTLPLUGIN_GLOBAL_H
#define TMCTLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TMCTLPLUGIN_LIBRARY)
#  define TMCTLPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TMCTLPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TMCTLPLUGIN_GLOBAL_H
